#spring.profiles.active=local
spring.application.name=tiendaErick
server.port=8087

spring.jackson.datatype.enum.write-enums-to-lowercase=true
spring.jackson.mapper.accept-case-insensitive-enums=true
spring.jackson.datatype.enum.read-unknown-enum-values-as-null=true

##Conexi�n a la BD
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}

##Se encarga de abrir la conexi�n f�sica, enviar las consultas SQL y traducir los resultados que devuelve la base de datos a un formato que Java entienda.
spring.datasource.driver-class-name=org.postgresql.Driver

##Crea y actualiza tablas autom�ticamente
spring.jpa.hibernate.ddl-auto=update

##Muestra en consola lo que hace hibernate debajo
spring.jpa.show-sql=true

##JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=3600000
jwt.refreshExpiration = 604800000

## Conmtraseñas
mama.pass=${PASS_MAMA}
papa.pass=${PASS_PAPA}
eri.pass=${PASS_ERI}
hermana.pass=${PASS_HERMANA}

## eyJhbGciOiJIUzI1NiJ9.eyJ0aXBvVG9rZW4iOiJhY2Nlc3MiLCJzdWIiOiJFcmljayIsImlkIjoiZmU4NzY4OWEtODE2MC00ZjQxLTg5ZjMtYTcyNTkwMWYxNjMzIiwiZXhwIjoxNzgyMzUwMjgxLCJub21icmUiOiJFcmljayIsIm51bWVyb1RlbGVmb25vIjoiMzExNTkxMDczNyJ9.np4_qTeWpVgOqjhqszS12IBVPnDoJReo7at4HiDjhcE