spring.application.name=tiendaErick
server.port=8087
spring.jackson.datatype.enum.write-enums-to-lowercase=true
spring.jackson.mapper.accept-case-insensitive-enums=true
spring.jackson.datatype.enum.read-unknown-enum-values-as-null=true

##Conexión a la BD
spring.datasource.url=jdbc:postgresql://localhost:5432/Tienda-Erick
spring.datasource.username=postgres
spring.datasource.password=

##Se encarga de abrir la conexión física, enviar las consultas SQL y traducir los resultados que devuelve la base de datos a un formato que Java entienda.
spring.datasource.driver-class-name=org.postgresql.Driver

##Crea y actualiza tablas automáticamente
spring.jpa.hibernate.ddl-auto=update

##Muestra en consola lo que hace hibernate debajo
spring.jpa.show-sql=true