spring.application.name=tiendaErick
server.port=8087
spring.jackson.datatype.enum.write-enums-to-lowercase=true
spring.jackson.mapper.accept-case-insensitive-enums=true
spring.jackson.datatype.enum.read-unknown-enum-values-as-null=true

##Conexi�n a la BD
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}

##Se encarga de abrir la conexi�n f�sica, enviar las consultas SQL y traducir los resultados que devuelve la base de datos a un formato que Java entienda.
spring.datasource.driver-class-name=org.postgresql.Driver

##Crea y actualiza tablas autom�ticamente
spring.jpa.hibernate.ddl-auto=update

##Muestra en consola lo que hace hibernate debajo
spring.jpa.show-sql=true

#   postgresql://postgres:GTbZyzrjQqkJDvQlAiiJHmerHRzMKRQE@metro.proxy.rlwy.net:53894/railway
#   jdbc:postgresql://postgres.railway.internal:5432/railway
#